import { useMemo, useState } from 'react';
import './ThieveryCalculator.css';
import { AGE_116_DATA, AGE_116_OPERATIONS, modifiedTpa, thieveryYield, optimalThieves, operationSuccessMetrics, watchTowersDamageReduction, watchTowersCatchChance, thievesDensLossReduction, stealthRecoveryPerTick, resolveThieveryModifiers } from '../../../src/thievery/index.js';
const pct = (value) => `${(value * 100).toFixed(2)}%`;
const num = (value, fallback = 0) => value === '' || value == null ? fallback : (Number.isFinite(Number(value)) ? Number(value) : fallback);
const ready = (value) => String(value ?? '').trim() !== '' && Number.isFinite(Number(value));
function Field({ label, value, onChange }) { return <label className="thievery-field"><span>{label}</span><input type="text" inputMode="decimal" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Select({ label, value, onChange, children }) { return <label className="thievery-field"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}>{children}</select></label>; }
function Auto({ label, value }) { return <div className="thievery-field"><span>{label}</span><strong>{value}</strong><small>Automatic from selected setup</small></div>; }
export default function ThieveryCalculator() {
  const data = AGE_116_DATA;
  const [race, setRace] = useState('Faery'), [personality, setPersonality] = useState('Rogue'), [ritual, setRitual] = useState('None'), [dragon, setDragon] = useState('None');
  const [targetRace, setTargetRace] = useState('Faery'), [targetPersonality, setTargetPersonality] = useState('Rogue'), [targetRitual, setTargetRitual] = useState('None'), [targetDragon, setTargetDragon] = useState('None');
  const [operation, setOperation] = useState('rob_vaults'), [war, setWar] = useState(false), [invisibility, setInvisibility] = useState(false), [guile, setGuile] = useState(false), [targetInvisibility, setTargetInvisibility] = useState(false), [targetIlluminate, setTargetIlluminate] = useState(false);
  const [selfAcres, setSelfAcres] = useState(''), [selfThieves, setSelfThieves] = useState(''), [selfNW, setSelfNW] = useState('');
  const [targetAcres, setTargetAcres] = useState(''), [targetThieves, setTargetThieves] = useState(''), [targetNW, setTargetNW] = useState(''), [targetResource, setTargetResource] = useState('');
  const [thievesDens, setThievesDens] = useState(''), [targetThievesDens, setTargetThievesDens] = useState(''), [targetWatchTowers, setTargetWatchTowers] = useState('');
  const [crimeScienceMultiplier, setCrimeScienceMultiplier] = useState(''), [targetCrimeScienceMultiplier, setTargetCrimeScienceMultiplier] = useState(''), [shieldingReduction, setShieldingReduction] = useState(''), [honorTpa, setHonorTpa] = useState(''), [targetHonorTpa, setTargetHonorTpa] = useState(''), [stealth, setStealth] = useState('');
  const op = AGE_116_OPERATIONS[operation];
  const resolved = useMemo(() => resolveThieveryModifiers({ age: 116, race, personality, ritual: ritual === 'None' ? undefined : ritual, dragon: dragon === 'None' ? undefined : dragon, invisibility, guile }), [race, personality, ritual, dragon, invisibility, guile]);
  const targetResolved = useMemo(() => resolveThieveryModifiers({ age: 116, race: targetRace, personality: targetPersonality, ritual: targetRitual === 'None' ? undefined : targetRitual, dragon: targetDragon === 'None' ? undefined : targetDragon, invisibility: targetInvisibility }), [targetRace, targetPersonality, targetRitual, targetDragon, targetInvisibility]);
  const calculations = useMemo(() => {
    const selfCrime = num(crimeScienceMultiplier, 1) * resolved.crimeScienceEffectivenessMultiplier;
    const targetCrime = num(targetCrimeScienceMultiplier, 1) * targetResolved.crimeScienceEffectivenessMultiplier;
    const selfReady = ready(selfAcres) && ready(selfThieves);
    const targetReady = ready(targetAcres) && ready(targetThieves);
    const selfTpa = selfReady ? modifiedTpa({ acres: num(selfAcres), thieves: num(selfThieves), thievesDensPct: num(thievesDens), thievesDensEffectivenessMultiplier: resolved.thievesDensEffectivenessMultiplier, crimeScienceMultiplier: selfCrime, racialTpaMultiplier: resolved.racialTpaMultiplier, personalityTpaMultiplier: resolved.personalityTpaMultiplier, honorTpaMultiplier: num(honorTpa, 1), ritualTpaMultiplier: resolved.ritualTpaMultiplier, invisibilityMultiplier: 1, dragonTpaMultiplier: resolved.dragonTpaMultiplier }) : null;
    const targetTpa = targetReady ? modifiedTpa({ acres: num(targetAcres), thieves: num(targetThieves), thievesDensPct: num(targetThievesDens), thievesDensEffectivenessMultiplier: targetResolved.thievesDensEffectivenessMultiplier, crimeScienceMultiplier: targetCrime, racialTpaMultiplier: targetResolved.racialTpaMultiplier, personalityTpaMultiplier: targetResolved.personalityTpaMultiplier, honorTpaMultiplier: num(targetHonorTpa, 1), ritualTpaMultiplier: targetResolved.ritualTpaMultiplier, invisibilityMultiplier: 1, dragonTpaMultiplier: targetResolved.dragonTpaMultiplier }) : null;
    const gains = war ? op?.gainsPerThiefWar : op?.gainsPerThiefNormal;
    const maxPercent = war ? op?.maxPercentWar : op?.maxPercentNormal;
    const thievesToSend = ready(targetResource) && gains != null && maxPercent != null ? optimalThieves(num(targetResource), maxPercent, gains, resolved.racialTpaMultiplier) : null;
    const targetDamageTaken = targetResolved.sabotageDamageTakenMultiplier * targetResolved.thieveryDamageTakenMultiplier;
    const yieldReady = selfReady && targetReady && ready(selfNW) && ready(targetNW) && ready(targetResource) && thievesToSend != null;
    const yieldResult = yieldReady ? thieveryYield({ thievesSent: thievesToSend, selfNetworth: num(selfNW), targetNetworth: num(targetNW), gainsPerThief: gains, resourcesLostFraction: op?.resourcesLostFraction ?? 0, modifiers: { racialMultiplier: resolved.racialTpaMultiplier, personalityMultiplier: resolved.personalityTpaMultiplier, scienceMultiplier: selfCrime, guileMultiplier: resolved.sabotageDamageMultiplier * resolved.sabotageDamageDealtMultiplier, cunningMultiplier: 1, targetRacialMultiplier: targetDamageTaken, targetPersonalityMultiplier: 1, targetIlluminateShadowsMultiplier: targetIlluminate ? 0.80 : 1, targetWatchtowersReduction: watchTowersDamageReduction(num(targetWatchTowers)), targetShieldingReduction: num(shieldingReduction), stanceMultiplier: 1, warBonus: war ? 1 : 0 } }) : null;
    const success = selfTpa && targetTpa && thievesToSend != null ? operationSuccessMetrics(selfTpa.value, targetTpa.value, { thievesSent: thievesToSend, totalThieves: num(selfThieves), dragonSuccessMultiplier: resolved.sabotageSuccessChanceMultiplier }) : null;
    return { selfTpa, targetTpa, yieldResult, thievesToSend, success, selfCrime, targetCrime };
  }, [selfAcres, selfThieves, selfNW, targetAcres, targetThieves, targetNW, targetResource, thievesDens, targetThievesDens, targetWatchTowers, crimeScienceMultiplier, targetCrimeScienceMultiplier, shieldingReduction, honorTpa, targetHonorTpa, operation, war, resolved, targetResolved, targetIlluminate, op]);
  const recovery = stealthRecoveryPerTick({ race, personality, dragon: dragon === 'None' ? undefined : dragon });
  const afterStealth = Math.max(0, num(stealth) / 100 - (op?.stealthCost ?? 0));
  return <div className="thievery-calculator">
    <div className="thievery-header"><div><h2>Thievery Calculator — Age 116</h2><p>Utopia War Room Age 116 mechanics. Modifiers from the selected setup are automatic.</p></div><div className="thievery-source-status"><span>✓ Verified</span><span>{data.source.name}</span></div></div>
    <div className="thievery-grid">
      <section className="thievery-panel"><h3>Our Province</h3><Select label="Race" value={race} onChange={setRace}>{Object.keys(data.races).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Personality" value={personality} onChange={setPersonality}>{Object.keys(data.personalities).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Ritual" value={ritual} onChange={setRitual}><option>None</option>{Object.keys(data.rituals).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Dragon" value={dragon} onChange={setDragon}><option>None</option>{Object.keys(data.dragons).map((x) => <option key={x}>{x}</option>)}</Select><Field label="Acres" value={selfAcres} onChange={setSelfAcres}/><Field label="Thieves" value={selfThieves} onChange={setSelfThieves}/><Field label="Networth" value={selfNW} onChange={setSelfNW}/><Auto label="Race TPA modifier" value={pct(resolved.racialTpaMultiplier - 1)}/><Auto label="Personality TPA modifier" value={pct(resolved.personalityTpaMultiplier - 1)}/><Auto label="Ritual TPA modifier" value={pct(resolved.ritualTpaMultiplier - 1)}/><Auto label="Dragon TPA modifier" value={pct(resolved.dragonTpaMultiplier - 1)}/><Field label="Thieves' Dens %" value={thievesDens} onChange={setThievesDens}/><Field label="Crime Science multiplier" value={crimeScienceMultiplier} onChange={setCrimeScienceMultiplier}/><Field label="Honor TPA multiplier" value={honorTpa} onChange={setHonorTpa}/><label className="thievery-check"><input type="checkbox" checked={invisibility} onChange={(e) => setInvisibility(e.target.checked)}/> Invisibility active (+10% TPA)</label><label className="thievery-check"><input type="checkbox" checked={guile} onChange={(e) => setGuile(e.target.checked)}/> Guile active (+10% sabotage damage)</label></section>
      <section className="thievery-panel"><h3>Target Province</h3><Select label="Race" value={targetRace} onChange={setTargetRace}>{Object.keys(data.races).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Personality" value={targetPersonality} onChange={setTargetPersonality}>{Object.keys(data.personalities).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Ritual" value={targetRitual} onChange={setTargetRitual}><option>None</option>{Object.keys(data.rituals).map((x) => <option key={x}>{x}</option>)}</Select><Select label="Dragon" value={targetDragon} onChange={setTargetDragon}><option>None</option>{Object.keys(data.dragons).map((x) => <option key={x}>{x}</option>)}</Select><Field label="Acres" value={targetAcres} onChange={setTargetAcres}/><Field label="Thieves" value={targetThieves} onChange={setTargetThieves}/><Field label="Networth" value={targetNW} onChange={setTargetNW}/><Field label="Target resource amount" value={targetResource} onChange={setTargetResource}/><Auto label="Race TPA modifier" value={pct(targetResolved.racialTpaMultiplier - 1)}/><Auto label="Personality TPA modifier" value={pct(targetResolved.personalityTpaMultiplier - 1)}/><Auto label="Ritual TPA modifier" value={pct(targetResolved.ritualTpaMultiplier - 1)}/><Auto label="Dragon TPA modifier" value={pct(targetResolved.dragonTpaMultiplier - 1)}/><Field label="Thieves' Dens %" value={targetThievesDens} onChange={setTargetThievesDens}/><Field label="Crime Science multiplier" value={targetCrimeScienceMultiplier} onChange={setTargetCrimeScienceMultiplier}/><Field label="Honor TPA multiplier" value={targetHonorTpa} onChange={setTargetHonorTpa}/><Field label="Watch Towers %" value={targetWatchTowers} onChange={setTargetWatchTowers}/><Field label="Shielding reduction" value={shieldingReduction} onChange={setShieldingReduction}/><label className="thievery-check"><input type="checkbox" checked={targetInvisibility} onChange={(e) => setTargetInvisibility(e.target.checked)}/> Target Invisibility active</label><label className="thievery-check"><input type="checkbox" checked={targetIlluminate} onChange={(e) => setTargetIlluminate(e.target.checked)}/> Target Illuminate Shadows active</label></section>
    </div>
    <section className="thievery-panel"><h3>Operation</h3><Select label="Operation" value={operation} onChange={setOperation}>{Object.values(AGE_116_OPERATIONS).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><label className="thievery-check"><input type="checkbox" checked={war} onChange={(e) => setWar(e.target.checked)}/> War</label><div className="thievery-result-line"><span>Relations</span><strong>{op?.relations ?? '—'}</strong></div><div className="thievery-result-line"><span>Stealth cost</span><strong>{pct(op?.stealthCost ?? 0)}</strong></div><Field label="Current stealth %" value={stealth} onChange={setStealth}/><div className="thievery-result-line"><span>After operation</span><strong>{pct(afterStealth)}</strong></div></section>
    <section className="thievery-panel thievery-results"><h3>Calculation</h3><div className="thievery-result-grid"><div><span>Our raw / modified TPA</span><strong>{calculations.selfTpa ? `${calculations.selfTpa.raw.toFixed(3)} / ${calculations.selfTpa.value.toFixed(3)}` : '—'}</strong></div><div><span>Target raw / modified TPA</span><strong>{calculations.targetTpa ? `${calculations.targetTpa.raw.toFixed(3)} / ${calculations.targetTpa.value.toFixed(3)}` : '—'}</strong></div><div><span>Off / def TPA ratio</span><strong>{calculations.success ? `${calculations.success.tpaRatio.toFixed(3)}×` : '—'}</strong></div><div><span>Randomization</span><strong>{calculations.success?.randomizationPercent == null ? '—' : pct(calculations.success.randomizationPercent)}</strong></div><div><span>Optimal thieves</span><strong>{calculations.thievesToSend == null ? '—' : calculations.thievesToSend.toLocaleString()}</strong></div><div><span>Predicted yield</span><strong>{calculations.yieldResult == null ? '—' : calculations.yieldResult.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}</strong></div><div><span>WT catch chance</span><strong>{pct(watchTowersCatchChance(num(targetWatchTowers)))}</strong></div><div><span>WT damage reduction</span><strong>{pct(watchTowersDamageReduction(num(targetWatchTowers)))}</strong></div><div><span>Our TD loss reduction</span><strong>{pct(thievesDensLossReduction(num(thievesDens)))}</strong></div><div><span>Stealth recovery</span><strong>+{recovery}/tick</strong></div><div><span>Success probability</span><strong>Source gives ratio, not curve</strong></div><div><span>Source</span><strong>Age 116 War Room ✓</strong></div></div></section>
    <section className="thievery-panel"><h3>Audit</h3><div className="thievery-modifier-list"><span>Our race: {race} ✓</span><span>Our personality: {personality} ✓</span><span>Target race: {targetRace} ✓</span><span>Target personality: {targetPersonality} ✓</span><span>Our Crime science: {calculations.selfCrime.toFixed(3)}×</span><span>Target Crime science: {calculations.targetCrime.toFixed(3)}×</span><span>Our TD effectiveness: {resolved.thievesDensEffectivenessMultiplier.toFixed(2)}×</span><span>Target TD effectiveness: {targetResolved.thievesDensEffectivenessMultiplier.toFixed(2)}×</span><span>Our sabotage damage: {(resolved.sabotageDamageMultiplier * resolved.sabotageDamageDealtMultiplier).toFixed(3)}×</span><span>Target damage taken: {(targetResolved.sabotageDamageTakenMultiplier * targetResolved.thieveryDamageTakenMultiplier).toFixed(3)}×</span><span>Sabotage success modifier: {resolved.sabotageSuccessChanceMultiplier.toFixed(3)}×</span></div></section>
    <div className="thievery-source-note">Source: Utopia War Room — Age 116. No unpublished success-probability equation is invented.</div>
  </div>;
}
