const crypto = require('crypto');
const supabaseService = require('./supabase');
const logger = require('./logger');

const STEWARDS = [
  { key:'capture', name:'Capture Steward', role:'lossless capture validation' },
  { key:'identity', name:'Identity Steward', role:'province/kingdom identity validation' },
  { key:'schema', name:'Schema Steward', role:'payload preservation and classification validation' },
  { key:'integrity', name:'Integrity Steward', role:'flow/queue/projection consistency validation' },
  { key:'knowledge', name:'Wiki Knowledge Steward', role:'authoritative Utopia wiki/ruleset validation' },
];
const SUPERVISOR_INTERVAL_MS=Math.max(5000,Number(process.env.SPARTAN_STEWARD_INTERVAL_MS||5000));
const KNOWLEDGE_INTERVAL_MS=Math.max(30000,Number(process.env.SPARTAN_KNOWLEDGE_STEWARD_INTERVAL_MS||60000));
const SWEEP_LIMIT=Math.max(1,Math.min(50,Number(process.env.SPARTAN_STEWARD_SWEEP_LIMIT||10)));
const REVALIDATE_AFTER_MS=Math.max(30000,Number(process.env.SPARTAN_STEWARD_REVALIDATE_AFTER_MS||300000));
let supervisorTimer=null,knowledgeTimer=null,supervisorRunning=false,knowledgeRunning=false;
function result(steward,decision,confidence,reason,details={}){return{steward,decision,confidence,reason,details};}
function fieldPaths(value,prefix='',out=[]){if(value==null)return out;if(Array.isArray(value)){out.push(prefix||'[]');value.slice(0,50).forEach((v,i)=>fieldPaths(v,`${prefix}[${i}]`,out));return out}if(typeof value!=='object'){out.push(prefix||'value');return out}for(const[k,v]of Object.entries(value)){const p=prefix?`${prefix}.${k}`:k;out.push(p);fieldPaths(v,p,out)}return out}
function runCapture(c){if(!c?.capture_id)return result('capture','quarantine',100,'capture_id missing');if(!c?.source)return result('capture','quarantine',100,'source missing');if(!c?.page_kind)return result('capture','quarantine',100,'page_kind missing');if(c.raw_payload==null)return result('capture','quarantine',100,'raw_payload missing');if(c.parsed_payload==null)return result('capture','quarantine',100,'parsed_payload missing');return result('capture','pass',100,'lossless capture envelope present',{rawType:Array.isArray(c.raw_payload)?'array':typeof c.raw_payload,parsedType:Array.isArray(c.parsed_payload)?'array':typeof c.parsed_payload,rawTextLength:String(c.raw_text||'').length})}
function runIdentity(flow,capture){const province=flow?.province_id||capture?.province_id||null,kingdom=flow?.kingdom_id||capture?.kingdom_id||null;if(!province&&!kingdom)return result('identity','warn',95,'capture has no province or kingdom identity; retained as global page',{scope:'global'});return result('identity','pass',100,'identity envelope accepted',{province_id:province,kingdom_id:kingdom})}
function runSchema(flow,capture){const rawFields=fieldPaths(capture?.raw_payload||{}),parsedFields=fieldPaths(capture?.parsed_payload||{}),kind=flow?.page_kind||capture?.page_kind||'unknown';if(kind==='unknown')return result('schema','warn',90,'page classification is unknown',{rawFields:rawFields.length,parsedFields:parsedFields.length});return result('schema','pass',100,'payload retained without destructive field filtering',{page_kind:kind,rawFields:rawFields.length,parsedFields:parsedFields.length})}

async function runIntegrity(sb,flow,queueId,projectionKey){
 if(!flow?.flow_id)return result('integrity','fail',100,'flow_id missing');
 const{data:projection,error}=await sb.from('spartan_state_projection').select('province_id,version,source_flow_id,updated_at').eq('province_id',projectionKey).maybeSingle();
 if(error)return result('integrity','fail',100,`projection lookup failed: ${error.message}`);
 if(!projection)return result('integrity','fail',100,'projection missing after processing');
 if(projection.source_flow_id!==flow.flow_id){
   const flowTime=Date.parse(flow.processed_at||flow.created_at||'')||0,projectionTime=Date.parse(projection.updated_at||'')||0;
   if(projectionTime>=flowTime){return result('integrity','pass',100,'projection is newer than this reprocessed/historical flow; retained as current',{queue_id:queueId,projection_version:projection.version,source_flow_id:projection.source_flow_id,flow_id:flow.flow_id,reprocessed:true})}
   return result('integrity','fail',100,'projection points to a newer required flow',{source_flow_id:projection.source_flow_id,flow_id:flow.flow_id,projection_updated_at:projection.updated_at,flow_processed_at:flow.processed_at||flow.created_at||null});
 }
 const{data:edge,error:edgeError}=await sb.from('spartan_data_edges').select('id,event_type,from_system,to_system').eq('flow_id',flow.flow_id).eq('event_type','projection').order('id',{ascending:false}).limit(1).maybeSingle();
 if(edgeError)return result('integrity','fail',100,`edge lookup failed: ${edgeError.message}`);if(!edge)return result('integrity','fail',100,'projection edge missing');
 return result('integrity','pass',100,'flow, projection and edge are consistent',{queue_id:queueId,projection_version:projection.version,edge_id:edge.id})
}
async function recordEvent(sb,flow,queueId,item){const{error}=await sb.from('spartan_steward_events').insert({steward_key:item.steward,flow_id:flow?.flow_id||null,capture_id:flow?.capture_id||null,queue_id:queueId||null,decision:item.decision,confidence:item.confidence,reason:item.reason,details:item.details||{}});if(error)logger.warn(`[SPARTAN STEWARD] event write failed steward=${item.steward}: ${error.message}`)}
async function updateRegistry(sb,item,metadata=null){const column=item.decision==='pass'||item.decision==='warn'?'processed_count':item.decision==='quarantine'?'quarantined_count':'error_count';const{data:current}=await sb.from('spartan_steward_registry').select(column).eq('steward_key',item.steward).maybeSingle();const update={[column]:Number(current?.[column]||0)+1,last_run_at:new Date().toISOString(),last_status:item.decision,updated_at:new Date().toISOString()};if(metadata)update.metadata=metadata;await sb.from('spartan_steward_registry').update(update).eq('steward_key',item.steward)}
async function persistRun(sb,flow,results,capture,knowledge={}){const bad=results.find(x=>x.decision==='quarantine'||x.decision==='fail'),decision=bad?(bad.decision==='fail'?'fail':'quarantine'):'accept',confidence=Math.min(...results.map(x=>Number(x.confidence||0)));const{error}=await sb.from('spartan_steward_runs').insert({capture_id:flow?.capture_id||null,source:flow?.source||null,page_kind:flow?.page_kind||null,province_id:flow?.province_id||null,kingdom_id:flow?.kingdom_id||null,decision:decision==='fail'?'quarantine':decision,confidence,steward_results:results,canonical_payload:capture?.parsed_payload||capture?.raw_payload||{},knowledge_source:knowledge.source||null,knowledge_age:knowledge.age||null,knowledge_refs:knowledge.refs||{}});if(error)logger.warn(`[SPARTAN STEWARD] run write failed: ${error.message}`);return{decision,confidence}}
async function loadCapture(sb,flow){if(!flow?.capture_id)return null;const{data,error}=await sb.from('spartan_capture_vault').select('id,capture_id,source,province_id,kingdom_id,page_kind,url,raw_text,raw_payload,parsed_payload,content_hash,captured_at').eq('capture_id',flow.capture_id).order('id',{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`steward capture lookup: ${error.message}`);return data||null}
async function run(flow,capture,queueId,projectionKey,options={}){const sb=supabaseService.getClient();if(!sb)throw new Error('Supabase client unavailable for Spartan Stewards');const results=[runCapture(capture),runIdentity(flow,capture),runSchema(flow,capture)];if(options.afterProjection)results.push(await runIntegrity(sb,flow,queueId,projectionKey));for(const item of results){await recordEvent(sb,flow,queueId,item);await updateRegistry(sb,item)}const persisted=await persistRun(sb,flow,results,capture);return{...persisted,results,runId:crypto.randomUUID()}}

async function countRows(sb,table,age){let q=sb.from(table).select('*',{count:'exact',head:true});if(['race_rules','personality_rules','personality_modifiers'].includes(table))q=q.eq('age_number',age);if(table==='game_rules')q=q.eq('age_number',age).eq('active',true);const{count,error}=await q;if(error)throw new Error(`${table} count failed: ${error.message}`);return Number(count||0)}
async function runKnowledge(sb){const{data:source,error}=await sb.from('spartan_wiki_knowledge_registry').select('source_key,source_name,source_url,age_number,authoritative,active,metadata,updated_at').eq('active',true).eq('authoritative',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)return result('knowledge','fail',100,`knowledge registry lookup failed: ${error.message}`);if(!source)return result('knowledge','quarantine',100,'no active authoritative wiki source registered');const counts={};try{for(const table of ['wiki_entries','race_rules','personality_rules','personality_modifiers','game_rules','province_modifiers'])counts[table]=await countRows(sb,table,source.age_number)}catch(e){return result('knowledge','fail',100,e.message,{source_key:source.source_key})}const missing=Object.entries(counts).filter(([,n])=>n<=0).map(([t])=>t);let status='unverified',length=null,hash=null;try{const r=await fetch(source.source_url,{redirect:'follow'});if(!r.ok)throw new Error(`authoritative source returned HTTP ${r.status}`);const text=await r.text();length=text.length;hash=crypto.createHash('sha256').update(text).digest('hex');status=new RegExp(`Age\\s*${Number(source.age_number)}`,'i').test(text)?'verified':'reachable_without_age_marker'}catch(e){return result('knowledge','warn',90,`knowledge tables are present but source could not be verified: ${e.message}`,{source_key:source.source_key,counts})}const decision=missing.length?'quarantine':status==='verified'?'pass':'warn';return result('knowledge',decision,missing.length?100:status==='verified'?100:90,missing.length?`authoritative knowledge source is missing populated rule tables: ${missing.join(', ')}`:status==='verified'?'authoritative wiki source reachable and Age-aligned; canonical rule tables populated':'authoritative wiki source reachable, but Age marker could not be confirmed',{source_key:source.source_key,source_name:source.source_name,source_url:source.source_url,age:source.age_number,source_status:status,source_length:length,source_sha256:hash,counts,metadata:source.metadata||{}})}
async function sweepKnowledge(){if(knowledgeRunning)return;const sb=supabaseService.getClient();if(!sb)return;knowledgeRunning=true;try{const item=await runKnowledge(sb),d=item.details||{},refs={source_key:d.source_key||null,source_status:d.source_status||null,source_length:d.source_length||null,source_sha256:d.source_sha256||null,counts:d.counts||{},verified_at:new Date().toISOString()};await updateRegistry(sb,item,{last_verified_at:refs.verified_at,last_status:item.decision,last_reason:item.reason,...refs});await recordEvent(sb,null,null,item);await sb.from('spartan_steward_runs').insert({capture_id:null,source:d.source_key||'wiki',page_kind:'wiki_knowledge',province_id:null,kingdom_id:null,decision:item.decision==='fail'||item.decision==='quarantine'?'quarantine':'accept',confidence:item.confidence,steward_results:[item],canonical_payload:{source:d.source_name||null,age:d.age||null,counts:d.counts||{}},knowledge_source:d.source_key||null,knowledge_age:d.age||null,knowledge_refs:refs})}catch(e){const item=result('knowledge','fail',100,`knowledge steward execution failed: ${e.message}`);await updateRegistry(sb,item,{last_status:'fail',last_reason:e.message});await recordEvent(sb,null,null,item);logger.error(`[SPARTAN KNOWLEDGE STEWARD] ${e.stack||e.message}`)}finally{knowledgeRunning=false}}

async function sweepRecentFlows(){if(supervisorRunning)return;const sb=supabaseService.getClient();if(!sb)return;supervisorRunning=true;try{const cutoff=new Date(Date.now()-REVALIDATE_AFTER_MS).toISOString();const{data:flows,error}=await sb.from('spartan_data_flow').select('flow_id,capture_id,source,page_kind,province_id,kingdom_id,status,processed_at,created_at').eq('status','processed').order('processed_at',{ascending:false}).limit(SWEEP_LIMIT);if(error)throw new Error(`steward flow sweep: ${error.message}`);for(const flow of flows||[]){const{data:latest}=await sb.from('spartan_steward_events').select('created_at').eq('flow_id',flow.flow_id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(latest?.created_at&&latest.created_at>cutoff)continue;const capture=await loadCapture(sb,flow);if(!capture){logger.warn(`[SPARTAN STEWARD SUPERVISOR] missing capture flow=${flow.flow_id}`);continue}const projectionKey=flow.province_id||flow.flow_id;const results=[runCapture(capture),runIdentity(flow,capture),runSchema(flow,capture),await runIntegrity(sb,flow,null,projectionKey)];for(const item of results){await recordEvent(sb,flow,null,item);await updateRegistry(sb,item)}await persistRun(sb,flow,results,capture);const bad=results.find(x=>x.decision==='fail'||x.decision==='quarantine');if(bad)logger.warn(`[SPARTAN STEWARD SUPERVISOR] ${bad.steward}=${bad.decision} flow=${flow.flow_id}: ${bad.reason}`)}}catch(e){logger.error(`[SPARTAN STEWARD SUPERVISOR] ${e.stack||e.message}`)}finally{supervisorRunning=false}}
function start(){if(supervisorTimer)return;logger.info(`[SPARTAN STEWARDS] autonomous supervisor enabled interval=${SUPERVISOR_INTERVAL_MS}ms sweep=${SWEEP_LIMIT} revalidate=${REVALIDATE_AFTER_MS}ms`);for(const steward of STEWARDS)logger.info(`[SPARTAN STEWARD] ${steward.name} ready role=${steward.role}`);sweepRecentFlows();sweepKnowledge();supervisorTimer=setInterval(sweepRecentFlows,SUPERVISOR_INTERVAL_MS);knowledgeTimer=setInterval(sweepKnowledge,KNOWLEDGE_INTERVAL_MS)}
function stop(){if(supervisorTimer)clearInterval(supervisorTimer);if(knowledgeTimer)clearInterval(knowledgeTimer);supervisorTimer=null;knowledgeTimer=null}
module.exports={start,stop,run,sweepRecentFlows,sweepKnowledge,runKnowledge,STEWARDS};
